name: Shell commands

on: [push]

jobs:
    
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            -name: echo a string
             run: echo "Hello, Security Gurus! This is our First GitHub Sction"
